### ISSUE TITLE
Easy and fast alternative to protontricks.

### ISSUE THREAD

**Issue by SakoPolis** [BepInEx/bepinex-docs#11]
Protontricks is not working for some users due to an issue with wow64 wine. Luckily there is a faster and simpler way to to the dll override for proton without using protontricks or even winecfg. In the steam launch options of the relevant game, simply put 
`WINEDLLOVERRIDES="winhttp.dll=n,b" %command%`

source: Vampire Hunter D on protondb: https://www.protondb.com/app/1966720

I can personally confirm that this fixes bepinex for Lethal Company proton without installing any additional software. Note that the bepinex terminal doesn't launch for me so it might not seem like it's working for you.

**Comment by simon300000** [comment]
This method works great for me also
